name: yatube_workflow

on: [push]

jobs:
#  tests:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up Python
#      uses: actions/setup-python@v2
#      with:
#        python-version: 3.8.2
#
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install flake8 pytest
#        pip install -r requirements.txt
#
#    - name: Lint with flake8
#      run: flake8

  deploy:
    runs-on: ubuntu-latest
    # needs: tests

    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~
            # sudo pkill -f gunicorn
            rm -rf hw05_final
            git clone https://alexfofanov:${{ secrets.ACCESS_TOKEN }}@github.com/alexfofanov/hw05_final.git
            cd hw05_final
            python3 -m venv venv
            source venv/bin/activate
            pip3 install --quiet -r requirements.txt
            python3 manage.py migrate --noinput
            python3 manage.py collectstatic --noinput
            sudo ./venv/bin/gunicorn --bind 0.0.0.0:80 yatube.wsgi --daemon

#  send_message:
#    runs-on: ubuntu-latest
#    needs: deploy
#
#    steps:
#      - name: send message
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_TO }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: ${{ github.workflow }} успешно выполнен!
